"""
Kevin Patel
"""
# *********** COMMON TO ALL CRUNCH PACKAGES ***********
import sys
from os.path import dirname, realpath

sys.path.insert(0, dirname(dirname(dirname(realpath(sys.argv[0])))))

# ********** SPECIFIC TO THIS CRUNCH PACKAGE **********
# DATA

from os import sep
from common_util import DATA_DIR

# PACKAGE CONSTANTS
dum=0
DR_NAME = 'data_record'
DR_FMT = 'csv'

DR_IDS = ['id', 'name', 'dir']						# Autogenerated columns
DR_REQ = ['freq', 'root', 'basis', 'stage', 'type']			# Minimum needed to dump a df
DR_META = ['cat', 'hist', 'desc']					# Other misc metadata (mutable: all)
DR_GEN = ['size', 'dumptime', 'hash', 'created', 'modified'] 		# Other autogenerated columns (mutable: all)
DR_COLS = DR_IDS + DR_REQ + DR_META + DR_GEN

DG_PFX = 'dg_'
CS_PFX = 'cs_'

ACCESS_UTIL_DIR = DATA_DIR +'access_util' +sep
VIEW_DIR = ACCESS_UTIL_DIR +'view' +sep

# PACKAGE DEFAULTS
default_cleanfile = 'clean.json'
default_viewfile_sfx = 'view'

